#!/usr/bin/env bash

rm -rf dist \
  && mkdir dist \
  && cp -r package.json LICENSE README.md src dist \
  && dot-json dist/package.json scripts --delete \
  && dot-json dist/package.json devDependencies --delete
